# Generated by Django 3.2.4 on 2021-06-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datatime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='datatime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='heading',
            new_name='title',
        ),
    ]
